#!/command/with-contenv bash
# shellcheck shell=bash

# This is an example of an s6-rc oneshot init script.
# It only runs once when the container boots! Suitable for installing dependencies.

echo "[Example Init] Installing extra software before anything boots!"
apk add --no-cache python3
