version: "3.3"

services:
  qbittorrent:
    build: ./
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24
      - HEALTH_CHECK_HOST=one.one.one.one
      - HEALTH_CHECK_INTERVAL=300
      - ENABLE_SSL=yes
      - UNPRIVILEGED=yes
    volumes:
      - '/server/qbittorrent/:/config'
    ports:
     # - 80:8080
      - 443:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1